server:
  port: 8087
  servlet:
    context-path: /api/authorization

management:
  server:
    port: 8187
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: auth
        format_sql: true
  liquibase:
    default-schema: auth
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: authorization-app

  kafka:
    consumer:
      group-id: user-group  # Установите группу потребителей
      bootstrap-servers: localhost:9092  # Адрес Kafka-сервера
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # Десериализатор для значения
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Десериализатор для ключа
      properties:
        spring.json.value.default.type: com.bank.authorization.dto.UserDto  # Тип данных для десериализации
    producer:
      bootstrap-servers: localhost:9092  # Адрес Kafka-сервера
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Сериализатор для значения
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Сериализатор для ключа


