# Kafka topic configuration for Bank
spring.kafka.topics.bank.create.name=public-info.bank.create
spring.kafka.topics.bank.update.name=public-info.bank.update
spring.kafka.topics.bank.delete.name=public-info.bank.delete
spring.kafka.topics.bank.get.name=public-info.bank.get

spring.kafka.topics.bank.create.response=public-info.bank.create.response
spring.kafka.topics.bank.update.response=public-info.bank.update.response
spring.kafka.topics.bank.delete.response=public-info.bank.delete.response
spring.kafka.topics.bank.get.response=public-info.bank.get.response

# Kafka topic configuration for Certificate
spring.kafka.topics.certificate.create.name=public-info.certificate.create
spring.kafka.topics.certificate.update.name=public-info.certificate.update
spring.kafka.topics.certificate.delete.name=public-info.certificate.delete
spring.kafka.topics.certificate.get.name=public-info.certificate.get

spring.kafka.topics.certificate.create.response=public-info.certificate.create.response
spring.kafka.topics.certificate.update.response=public-info.certificate.update.response
spring.kafka.topics.certificate.delete.response=public-info.certificate.delete.response
spring.kafka.topics.certificate.get.response=public-info.certificate.get.response

# Kafka topic configuration for License
spring.kafka.topics.license.create.name=public-info.license.create
spring.kafka.topics.license.update.name=public-info.license.update
spring.kafka.topics.license.delete.name=public-info.license.delete
spring.kafka.topics.license.get.name=public-info.license.get

spring.kafka.topics.license.create.response=public-info.license.create.response
spring.kafka.topics.license.update.response=public-info.license.update.response
spring.kafka.topics.license.delete.response=public-info.license.delete.response
spring.kafka.topics.license.get.response=public-info.license.get.response

# Kafka topic configuration for Branch
spring.kafka.topics.branch.create.name=public-info.branch.create
spring.kafka.topics.branch.update.name=public-info.branch.update
spring.kafka.topics.branch.delete.name=public-info.branch.delete
spring.kafka.topics.branch.get.name=public-info.branch.get

spring.kafka.topics.branch.create.response=public-info.branch.create.response
spring.kafka.topics.branch.update.response=public-info.branch.update.response
spring.kafka.topics.branch.delete.response=public-info.branch.delete.response
spring.kafka.topics.branch.get.response=public-info

# Kafka topic configuration for ATM
spring.kafka.topics.atm.create.name=public-info.atm.create
spring.kafka.topics.atm.update.name=public-info.atm.update
spring.kafka.topics.atm.delete.name=public-info.atm.delete
spring.kafka.topics.atm.get.name=public-info.atm.get

spring.kafka.topics.atm.create.response=public-info.atm.create.response
spring.kafka.topics.atm.update.response=public-info.atm.update.response
spring.kafka.topics.atm.delete.response=public-info.atm.delete.response
spring.kafka.topics.atm.get.response=public-info.atm.get.response

spring.kafka.groups.bank=public-info-bank-group
spring.kafka.groups.atm=public-info-atm-group
spring.kafka.groups.branch=public-info-branch-group
spring.kafka.groups.certificate=public-info-certificate-group
spring.kafka.groups.license=public-info-license-group

